/*
# Add permanent membership codes

1. New Column on `public.profiles`
- `membership_code`: unique, human-readable membership identifier for every member.
- New members receive a generated `WV-XXXXXXXX` code automatically.

2. Existing Data
- Existing profiles receive a stable code derived from their profile ID.
- No member rows or existing profile values are removed or changed.

3. Security
- No RLS policy is changed. The code follows the same access rules as other profile fields.
- A unique index prevents duplicate membership codes.

4. Important Notes
- The code is generated by the database, so it cannot be accidentally duplicated by the signup or admin forms.
- The value is available to member cards, detail views, and exports.
*/

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS membership_code text;

ALTER TABLE public.profiles
  ALTER COLUMN membership_code SET DEFAULT (
    'WV-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
  );

UPDATE public.profiles
SET membership_code = 'WV-' || upper(substr(replace(id::text, '-', ''), 1, 8))
WHERE membership_code IS NULL;

ALTER TABLE public.profiles
  ALTER COLUMN membership_code SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_membership_code_key
  ON public.profiles (membership_code);
